language: cpp
compiler:
    - gcc
sudo: false
addons:
    apt:
        packages:
        - lib32stdc++6
        - lib32z1-dev
        - libc6-dev-i386
        - linux-libc-dev
        
        - lib32gcc-5-dev
        - libgcc-5-dev
        - g++-5-multilib
        - gcc-5-multilib
        - g++-5
        - gcc-5
        
        - realpath
        sources:
            - ubuntu-toolchain-r-test
    cache:
        directories:
            - ../mysql-5.0
    
install:
    - git clone https://github.com/alliedmodders/sourcemod.git --recursive -b 1.8-dev $TRAVIS_BUILD_DIR/../sourcemod
    - cd $TRAVIS_BUILD_DIR/../
    - wget https://raw.githubusercontent.com/alliedmodders/sourcemod/master/tools/checkout-deps.sh && chmod +x checkout-deps.sh
    - ./checkout-deps.sh
    #fixing some dumb issues {
    - mkdir -p $TRAVIS_BUILD_DIR/../include/asm
    - cp -r /usr/include/asm-generic/* $TRAVIS_BUILD_DIR/../include/asm/
    #}
    
script:
    - mkdir $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
    #again, fixing some dumb issues {
    - export CPLUS_INCLUDE_PATH=$(realpath $TRAVIS_BUILD_DIR/../include)
    #}
    - CXX=g++-5 CC=gcc-5 python ../configure.py --enable-optimize
    - ambuild
    
before_deploy: 
    - cd $TRAVIS_BUILD_DIR/build/package/addons/sourcemod
    - zip -r $TRAVIS_BUILD_DIR/think_hooks.zip ./extensions/ ./scripting/
    - cd $TRAVIS_BUILD_DIR

deploy:
    provider: releases
    api_key:
        secure: E7x8bzKURuQKPcjXHhiyxWrfLlEuHkY9J4i43LM6cRgTIy6N7Ajatxr+QV5RuwPoW1chfYrICUPCmg2XIAmyxqGQc0KHIUmb3s4K1+enmwsxm7RDA95sJx3aCfQPxqEavNO22kFUlMgib67o2NIFD8986gpiUv07SE8DOiNd87aiaZZ4gXjQTEncYLutVRCAxkg5uEM1F2+23tgVaK5otiPDtniUqGu9hbnoaRCaoWbmWPJ2WD1d+xGoQOfHV2rhfruVhnKnUkWESFa0snJ5Yf4v4dQ/os5WZkBLnSWiIGtEU/eGuxxVMqfZOsLkfciGjgtIZ3w/OqVSSRHZgRUZREob89dLZ7+Rt/BPsQ5fU7k1b7jjCGawCMsYtva8f9wJUWnefOGg4w/Cw4F/izqRj5oV4Evre5BdYIsX1MC+THVmT3CbCeaZSB7QZ3X2ZRfCJYxn3k0Ywkte1bdI4SigfeE/LzP0UC20B3s0DAm4UJxgF5D0/2vGv3yfrpboYcPQpwZ4TJkNeNkAQzGRd7OaT2qVuko9H5r6j/gkLYXYy47d17in1XPKslX/sCYhfA6kSSwG+UR/KNGJKsr/vlI79lk5TnaN1FLpmh5ve1rvNCEnjB0giwCS+7MB+mkNr+zdtAcnbLi6pSRoPeEaMqXrCMENSz7mIPaHCSvivh0XnZg=
    file: think_hooks.zip
    on:
        repo: fakuivan/Think-Hooks
        tags: true
        all_branches: true